#!/usr/bin/env python3
"""
Sparkmage
"""
import fire
from acquire.image import ImageAcquisition
from analysis.caller import Caller
from storage.hadoopfs import HDFS
from visualize.visualization import ImageVisualization

class Sparkmage(ImageAcquisition, Caller, HDFS, ImageVisualization):
    """
    Sparkmage

    Sparkmage :: Image clustering framework
    """

if __name__ == '__main__':
    fire.Fire(Sparkmage)
